"""
Knowledge feedback loop for the FinMate lending agent.
This module handles the detection of knowledge gaps and automatic ingestion of new information.
"""

import os
import json
import datetime
import asyncio
from typing import Dict, List, Optional, Union, Any
from pydantic import BaseModel, Field
from langchain_core.tools import tool
from graphiti_core import Graphiti
from langchain_openai import ChatOpenAI

# Initialize Graphiti client
graphiti = Graphiti(
    os.environ.get("NEO4J_URI"),
    os.environ.get("NEO4J_USER"),
    os.environ.get("NEO4J_PASSWORD")
)

# Set up enhanced logging for Graphiti operations
def log_graphiti_operation(operation_type, details):
    """Log Graphiti operations with timestamp and details"""
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{timestamp}] GRAPHITI {operation_type}: {details}")


# Initialize LLM for generating answers to knowledge gaps
llm = ChatOpenAI(
    model="gpt-4o",
    temperature=0.2  # Lower temperature for more factual responses
)

class KnowledgeGap(BaseModel):
    """Model for representing a knowledge gap."""
    query: str = Field(..., description="The user query that couldn't be answered from the knowledge graph")
    generated_answer: str = Field(..., description="The answer generated by the LLM")
    confidence: float = Field(default=0.7, description="Confidence in the generated answer (0.0-1.0)")
    source: str = Field(default="llm", description="Source of the answer")
    entity_type: str = Field(default="FinancialConcept", description="Type of entity this knowledge relates to")

@tool
async def handle_knowledge_gap(
    query: str,
    search_results: str,
    entity_type: str = "FinancialConcept"
) -> str:
    """
    Handle a knowledge gap by generating an answer and adding it to the knowledge graph
    as a structured fact triplet.
    
    Args:
        query: The user query that couldn't be answered from the knowledge graph
        search_results: The search results from the knowledge graph (may be empty or insufficient)
        entity_type: Type of entity this knowledge relates to (e.g., 'LoanProduct', 'FinancialConcept')
    
    Returns:
        The generated answer along with a confirmation that it has been added to the knowledge graph
    """
    print(f"Handling knowledge gap for query: {query}")
    print(f"Search results: {search_results}")
    
    # Check if search results are empty or insufficient
    if not search_results or search_results == "No information found for your query.":
        # Generate an answer using the LLM
        prompt = f"""
        You are a financial expert specializing in lending products and concepts.
        Please provide a factual, concise answer to the following question:
        
        {query}
        
        Your answer should be accurate, educational, and suitable for adding to a knowledge base.
        Focus only on providing factual information without opinions or marketing language.
        """
        
        response = await llm.ainvoke(prompt)
        generated_answer = response.content
        
        # Now let's also generate a structured fact triplet from this answer
        triplet_prompt = f"""
        Based on the following question and answer, extract a structured fact triplet in the format:
        [Subject] [Relationship] [Object]
        
        Question: {query}
        Answer: {generated_answer}
        
        For example:
        - Personal loans [HAVE_INTEREST_RATE] 8.5% APR
        - Secured loans [REQUIRE] collateral
        - Credit score [AFFECTS] loan eligibility
        
        Extract the most important fact triplet from the answer:
        """
        
        triplet_response = await llm.ainvoke(triplet_prompt)
        fact_triplet = triplet_response.content.strip()
        
        # Parse the triplet into subject, relationship, and object
        try:
            # Try to extract the components from the triplet
            import re
            triplet_match = re.match(r'(.*?)\s+\[(.*?)\]\s+(.*)', fact_triplet)
            
            if triplet_match:
                subject = triplet_match.group(1).strip()
                relationship = triplet_match.group(2).strip()
                object_value = triplet_match.group(3).strip()
            else:
                # Fallback parsing if the format isn't exactly as expected
                parts = fact_triplet.split(' ')
                if len(parts) >= 3:
                    # Simple heuristic: first word is subject, last word is object, middle is relationship
                    subject = parts[0]
                    relationship = ' '.join(parts[1:-1])
                    object_value = parts[-1]
                else:
                    # If we can't parse it properly, use default values
                    subject = query.split(' ')[0]  # Use first word of query as subject
                    relationship = "HAS_INFORMATION"
                    object_value = "financial concept"
            
            # Add the generated answer to the knowledge graph as a fact triplet
            try:
                from graphiti_core.nodes import EntityNode
                from graphiti_core.edges import EntityEdge
                import uuid
                
                # Create UUIDs for the nodes
                source_uuid = str(uuid.uuid4())
                target_uuid = str(uuid.uuid4())
                
                # Create the source and target nodes
                source_node = EntityNode(
                    uuid=source_uuid,
                    name=subject,
                    group_id="",
                    summary=f"Financial concept: {subject}"
                )
                
                target_node = EntityNode(
                    uuid=target_uuid,
                    name=object_value,
                    group_id="",
                    summary=f"Financial concept: {object_value}"
                )
                
                # Create the edge with the relationship and full answer as the fact
                edge = EntityEdge(
                    group_id="",
                    source_node_uuid=source_uuid,
                    target_node_uuid=target_uuid,
                    created_at=datetime.datetime.now(),
                    name=relationship,
                    fact=generated_answer  # Store the full answer as the fact
                )
                
                # Add the triplet to the graph
                await graphiti.add_triplet(source_node, edge, target_node)
                
                log_graphiti_operation(
                    "ADD_FACT_TRIPLET", 
                    f"Subject: '{subject}', Relationship: '{relationship}', Object: '{object_value}'"
                )
                
                # Also add as an episode for good measure (belt and suspenders approach)
                episode = {
                    "text": f"Question: {query}\nAnswer: {generated_answer}",
                    "metadata": {
                        "source": "llm",
                        "confidence": 0.7,
                        "timestamp": datetime.datetime.now().isoformat(),
                        "entity_type": entity_type,
                        "query": query,
                        "triplet": f"{subject} [{relationship}] {object_value}"
                    }
                }
                
                await graphiti.ingest_episode(episode)
                
                log_graphiti_operation(
                    "ADD_EPISODE", 
                    f"Query: '{query[:50]}...', Entity Type: '{entity_type}', Related Triplet: '{subject} [{relationship}] {object_value}'"
                )
                
                return f"""
                {generated_answer}
                
                (This information has been added to our knowledge base as a fact: {subject} [{relationship}] {object_value})
                """
            except Exception as e:
                print(f"Error adding fact triplet to graph: {str(e)}")
                # Fallback to episode ingestion if triplet fails
                try:
                    episode = {
                        "text": f"Question: {query}\nAnswer: {generated_answer}",
                        "metadata": {
                            "source": "llm",
                            "confidence": 0.7,
                            "timestamp": datetime.datetime.now().isoformat(),
                            "entity_type": entity_type,
                            "query": query
                        }
                    }
                    
                    await graphiti.ingest_episode(episode)
                    
                    log_graphiti_operation(
                        "ADD_FALLBACK_EPISODE", 
                        f"Query: '{query[:50]}...', Entity Type: '{entity_type}' (Fallback after triplet failure)"
                    )
                    
                    return f"""
                    {generated_answer}
                    
                    (This information has been added to our knowledge base for future reference.)
                    """
                except Exception as e2:
                    print(f"Error adding episode to graph: {str(e2)}")
                    return f"""
                    {generated_answer}
                    
                    (Note: I was unable to add this information to our knowledge base due to a technical issue.)
                    """
        except Exception as e:
            print(f"Error parsing fact triplet: {str(e)}")
            return f"""
            {generated_answer}
            
            (Note: I was unable to add this information to our knowledge base due to a technical issue.)
            """
    else:
        # If we have search results, just return them
        return search_results

@tool
async def answer_with_knowledge_feedback(
    query: str
) -> str:
    """
    Answer a query using the knowledge graph, and if no information is found,
    generate an answer and add it to the knowledge graph.
    
    Args:
        query: The user query to answer
    
    Returns:
        The answer, either from the knowledge graph or generated by the LLM
    """
    print(f"Answering with knowledge feedback for query: {query}")
    
    try:
        # First, try to find information in the knowledge graph
        results = await graphiti.search(query)
        
        if not results:
            print("No results found in knowledge graph, generating answer...")
            # No results found, generate an answer and add it to the knowledge graph
            return await handle_knowledge_gap(
                query=query,
                search_results="No information found for your query.",
                entity_type="FinancialConcept"
            )
        else:
            # Format the results into a readable string
            formatted_results = []
            for edge in results:
                content = getattr(edge, 'fact', 'No content available.')
                formatted_results.append(f"- {content}")
            
            return "\n".join(formatted_results)
            
    except Exception as e:
        print(f"Error in answer_with_knowledge_feedback: {str(e)}")
        # If there's an error, fall back to the LLM
        response = await llm.ainvoke(f"Please answer this financial question: {query}")
        return f"""
        {response.content}
        
        (Note: I was unable to check our knowledge base due to a technical issue.)
        """
